/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CustomAirdrop1155Merkle } from "./CustomAirdrop1155Merkle";
export type { IERC1155 } from "./IERC1155";
