/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as customAirdrop1155ClaimMerkleSol from "./CustomAirdrop1155ClaimMerkle.sol";
export type { customAirdrop1155ClaimMerkleSol };
import type * as erc1155Sol from "./Erc1155.sol";
export type { erc1155Sol };
import type * as erc20Sol from "./Erc20.sol";
export type { erc20Sol };
import type * as typesSol from "./Types.sol";
export type { typesSol };
export type { Administrable } from "./Administrable";
export type { AirdropManager } from "./AirdropManager";
export type { CustomAirdrop1155 } from "./CustomAirdrop1155";
export type { OpenAirdropERC20 } from "./OpenAirdropERC20";
