/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as airdropManagerSol from "./AirdropManager.sol";
export type { airdropManagerSol };
import type * as customAirdrop1155Sol from "./CustomAirdrop1155.sol";
export type { customAirdrop1155Sol };
import type * as customAirdrop1155ClaimMerkleSol from "./CustomAirdrop1155ClaimMerkle.sol";
export type { customAirdrop1155ClaimMerkleSol };
import type * as erc1155Sol from "./Erc1155.sol";
export type { erc1155Sol };
export type { Administrable } from "./Administrable";
