

export const AIRDROP_MANAGER_ADDRESS = process.env.NEXT_PUBLIC_AIRDROP_MANAGER_ADDRESS;
export const EXPLORER = process.env.NEXT_PUBLIC_EXPLORER;

export const FETCH_STATUS = {
  INIT: 'INIT',
  WAIT_WALLET: 'WAIT_WALLET',
  WAIT_TX: 'WAIT_TX',
  COMPLETED: 'COMPLETED',
  ERROR: "ERROR",
}