/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IAirdrop__factory } from "./IAirdrop__factory";
export { IERC1155__factory } from "./IERC1155__factory";
export { IERC20__factory } from "./IERC20__factory";
