/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAirdrop } from "./IAirdrop";
export type { IERC1155 } from "./IERC1155";
export type { IERC20 } from "./IERC20";
